server:
  port: '9002'
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

product-service-location: "http://localhost:9001"